version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}  # Pass PORT dynamically from .env
    ports:
      - "${PORT}:${PORT}"  # Map host port to container port dynamically
    env_file:
      - .env  # Load environment variables from .env
    command: ["sh", "-c", "npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run start -- -p $PORT"]

