export enum TaskType {
    LAUNCH_BROWSER = "LAUNCH_BROWSER",
    PAGE_TO_HTML = "PAGE_TO_HTML",
    EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
    EXTRACT_DATA_WITH_AI = "EXTRACT_DATA_WITH_AI",
    AGENTKIT_SWAP = "AGENTKIT_SWAP",
    SMART_CONTRACT_INTERACTION = "SMART_CONTRACT_INTERACTION",
    CREATE_RECALL_BUCKET = "CREATE_RECALL_BUCKET",
    STORE_AI_OUTPUT_RECALL = "STORE_AI_OUTPUT_RECALL",
    REASONING_LLM = "REASONING_LLM",
    MARKET_ANALYST_AGENT = "MARKET_ANALYST_AGENT",
    NEWS_ANALYST_AGENT = "NEWS_ANALYST_AGENT",
    TRADING_AGENT = "TRADING_AGENT",
    REFLECTION_AGENT = "REFLECTION_AGENT",
    RISK_MANAGEMENT = "RISK_MANAGEMENT",
    ORDER_FORMATTING = "ORDER_FORMATTING",
    BALANCE_FETCH = "BALANCE_FETCH",
    NEWS_AI_SEARCH = "NEWS_AI_SEARCH",
    NEWS_API = "NEWS_API",
    COINGECKO_MARKET_CHART = "COINGECKO_MARKET_CHART",
    MERGE_INPUTS = "MERGE_INPUTS",
    POSITION_STATE_LOADER_ONCHAIN = "POSITION_STATE_LOADER_ONCHAIN",
    PAIR_SELECTOR = "PAIR_SELECTOR",
    MARKET_PREPROCESSOR = "MARKET_PREPROCESSOR",
    BOX_STRATEGY_SELECTOR = "BOX_STRATEGY_SELECTOR",
    SIGNAL_GENERATOR = "SIGNAL_GENERATOR",
    BOX_RISK_MANAGEMENT = "BOX_RISK_MANAGEMENT",
    CONDITION_ROUTER = "CONDITION_ROUTER",
}

export enum TaskParamType {
    STRING = "STRING",
    BROWSER_INSTANCE = "BROWSER_INSTANCE",
    SELECT = "SELECT",
    CREDENTIAL = "CREDENTIAL",
  }
  
  export interface TaskParam {
    name: string;
    type: TaskParamType;
    helperText?: string;
    required?: boolean;
    hideHandle?: boolean;
    value?: string;
    [key: string]: any;
  }
